### PR TITLE
New network

### PR DESCRIPTION
**Pull request by sekkurocode**
I readded the network and added functionality to balancedaccuracy.py. If you are able to test the balanced accuracy and network please do. I didn't quite manage to test it properly.

### CODE REVIEW

**Comment by heyitsalina** [comment]
for me it says that the branch has conflicts that must be resolved and it names the network and balanced accuracy files so we need to take a look at this issue before merging i guess

**Comment by sekkurocode** [comment]
The thing is, there's nothing on our master branch in the network.py and balancedaccuracy.py files that should conflict.

**Comment by sekkurocode** [comment]
Just look at the changes that were made(there aren't a lot of lines anyways) and see if there's anything disruptive. As far as i could see the changes arent that radical. Maybe we just ask Mr Müller tomorrow if he sees anything.

**Comment by sekkurocode** [comment]
You can look at the conflicts by pressing the "resolve conflicts" button. I don't get why, but it seems to take me replacing nothing with my code, as a merge conflict. Anyways i think it's good to merge

**Comment by heyitsalina** [comment]
i will merge it for now and if it brings up any more issues, we can work on fixing this

**Review by heyitsalina — APPROVED** [review]
good work!!

**Pull request merged**
